name: jajvm
description: A sample command-line application.
version: 0.1.0
homepage: https://github.com/jajvm/jajvm

# Remove this line later
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  # This only supports windows. Use prompts package for other platforms.
  cli_dialog: ^0.5.0
  cli_notify: ^0.0.3
  cli_util: ^0.3.5
  console: ^4.1.0
  dcli: ^1.30.2
  jajvm_core:
    git: git@github.com:jajvm/jajvm_core.git
  prompts: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  jajvm:
