name: jajvm
description: A sample command-line application.
version: 0.1.0
homepage: https://github.com/jajvm/jajvm

# Remove this line later
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  jajvm:
